"""Init

Revision ID: f1b35b7e7d53
Revises: 78a8c89c1cfe
Create Date: 2022-12-15 12:12:02.661996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b35b7e7d53'
down_revision = '78a8c89c1cfe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('contacts', sa.Column('name', sa.String(length=120), nullable=False))
    op.drop_column('contacts', 'fullname')
    op.drop_column('contacts', 'cell_phone')
    op.drop_column('contacts', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('contacts', sa.Column('cell_phone', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('contacts', sa.Column('fullname', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('contacts', 'name')
    op.drop_table('phones')
    op.drop_table('emails')
    # ### end Alembic commands ###
